### ISSUE TITLE
why does `build_docs.yml` still run on *every* PR?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/access#74]
I am not sure why the [`build_docs.yml`](https://github.com/pysal/access/blob/6ec2ebc8e6175013afc343eafc5ff5345c6c534f/.github/workflows/build_docs.yml) action keeps running on every PR, etc.

The following in `access`:

https://github.com/pysal/access/blob/6ec2ebc8e6175013afc343eafc5ff5345c6c534f/.github/workflows/build_docs.yml#L5-L7

seems to match exactly that in other ecosystem packages that only run on pushes tagged with a `v*`, for example [in `mapclassify`](https://github.com/pysal/mapclassify/blob/ded496a0d86ad9a5bebd63d293bf31148a653d62/.github/workflows/build_docs.yml#L5-L8 ):

```yaml
   push:
     # Sequence of patterns matched against refs/tags
     tags:
       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
```

So I must be missing something obvious, but I can't put my finger on it. Any thoughts?

@JamesSaxon @martinfleis @knaaptime 

-------------------------

* xref
  * #71
